name: CI

on:
  push:
    branches:
      - '**'

jobs:
  macOS:
    runs-on: macos-latest
    steps:
      - name: Install Checkout
        uses: actions/checkout@v4
      - name: Install Python
        id: install-python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Run Python stuff in order
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install cairosvg
          python ./Linux.py
          python ./macOS.py
          python ./__main__.py
          ls -la venv
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install Checkout
        uses: actions/checkout@v4
      - name: Install Python
        id: install-python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Run Python stuff in order
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install cairosvg
          python ./Linux.py
          python ./__main__.py
          ls -la venv
  Windows:
    runs-on: windows-latest
    steps:
      - name: Install Checkout
        uses: actions/checkout@v4
      - name: Install Python
        id: install-python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Run Python stuff in order
        run: |
          python -m venv venv
          ./venv/Scripts/activate
          pip install cairosvg
          python ./Linux.py
          python ./Windows.py
          python ./__main__.py
          ls venv
